spring.datasource.url=jdbc:mysql://altaria.proxy.rlwy.net:43579/railway
spring.datasource.username=root
spring.datasource.password=DEWuIjZSptOqfvrDoFOgdjBLRsBVmWNZ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true